Organize notes.md and .env-example
Bot-detector/bot-detector-discord-bot pull request #143
Opened 2022-07-13 22:17 UTC by Ferrariic

+ Moves setup to notes.md
+ Creates .env-example

2022-07-14 15:51 UTC, extreme4all requested changes

2022-07-14 15:51 UTC, extreme4all commented on .env-example
> +SUBMIT_RECIPIENT =
most of these are not used

2022-07-14 15:53 UTC, Ferrariic commented on .env-example
> +SUBMIT_RECIPIENT =
I think I pulled these from the wrong config, ex. Legacy. I'll change this.

2022-07-22 12:02 UTC, extreme4all requested changes

2022-07-22 12:02 UTC, extreme4all commented on .env-example
> +API_TOKEN =
Can you add the token, prefix & api token from the docker-compose.yml

2022-08-21 12:44 UTC, merged